version: "3.8"
services:
  db:
    image: postgres:15
    container_name: postgres-dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345}
      POSTGRES_DB: ${POSTGRES_DB:-prueba}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data\
    networks:
      - kfullnet

  ms-kfullstack:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/prueba
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: public
      JWT_SECRET: W91clN1cGVyU2VjdXJlSnd0U2VjcmV0S2V5V2l0aEF0TGVhc3Q2NENoYXJhY3RlcnNfMDEyMzQ1Njc4OWFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6QUJDREVGRw
      JWT_EXPIRATION: 86400000
    ports:
      - "8080:8080"
    networks:
      - kfullnet

volumes:
  postgres_data:

networks:
  kfullnet:
